[RSDK-8219] allow micro-RDK to build w/out provisioning feature
viamrobotics/micro-rdk pull request #267
Opened 2024-07-16 17:47 UTC by gvaradarajan

2024-07-17 17:39 UTC, mattjperez approved these changes
LGTM, just a non-blocking question about trait methods

2024-07-17 18:03 UTC, acmorrow requested changes
Looks pretty good. I'm not sure though why the ability to store robot credential is feature gated?

2024-07-17 18:03 UTC, acmorrow commented on micro-rdk/src/esp32/entry.rs
>      let (network, app_client) = 'provisioned: loop {
If you rename it here, rename it in `native` too please.

2024-07-17 18:03 UTC, acmorrow commented on micro-rdk/src/native/entry.rs
> +                    let _ = duration.insert(std::time::Duration::from_secs(3));
Why change this? It is now subtly different from the `esp32` version here.

2024-07-17 18:34 UTC, mattjperez commented on micro-rdk/src/native/exec.rs
> +use crate::common::webrtc::exec::WebRtcExecutor;
I don't think gating inside the block works typically. it's why I usually end up taking the same approach as here or just writing out the full/partial path where I'm using for one less feature-gate line

2024-07-17 20:26 UTC, gvaradarajan commented on micro-rdk/src/common/credentials_storage.rs
> +    #[cfg(feature = "provisioning")]
it's because `CloudConfig` is only available in the provisioning proto, which is feature-gated to provisioning

2024-07-17 21:23 UTC, acmorrow approved these changes
This LGTM. Please eliminate the small divergence between the two entry files that was introduced before commit.

2024-07-17 21:58 UTC, gvaradarajan commented on micro-rdk/src/common/credentials_storage.rs
> +#[cfg(feature = "provisioning")]
Again, this is because `CloudConfig` and `SetNetworkCredentialsRequest` are in the provisioning proto

2024-07-17 21:59 UTC, gvaradarajan commented on micro-rdk/src/native/exec.rs
> +use crate::common::webrtc::exec::WebRtcExecutor;
^ what he said

2024-07-17 22:01 UTC, gvaradarajan commented on micro-rdk/src/esp32/exec.rs
> +use crate::common::provisioning::server::ProvisioningExecutor;
I don't think so. A clarification on my response to the comment above, the following is invalid
```rust
use crate::common::{
    #[cfg(feature = "provisioning")]
    provisioning::server::ProvisioningExecutor,
    webrtc::exec::WebRtcExecutor
};
```

2024-07-18 20:34 UTC, npmenard approved these changes
LGTM

2024-07-18 21:11 UTC, merged