update hyper
viamrobotics/micro-rdk pull request #297
Opened 2024-08-21 20:29 UTC by mattjperez

verifying everything works the same. wasn't prompted for other code changes

2024-08-22 14:03 UTC, acmorrow requested changes

2024-08-22 14:14 UTC, mattjperez commented on Cargo.lock
> + "socket2 0.4.10",
weird. that's what was resolved using `cargo update hyper`.

checking the `cargo-tree`, it doesn't appear to have been a dependency for anything else. don't know why that got backed down. 

Looking into `socket2` they support two versions at any given time, right now, v4 and v5, on different branches but neither are the tagged release on github.

bumping back up and testing.

2024-08-22 14:31 UTC, mattjperez commented on Cargo.lock
> + "socket2 0.4.10",
@acmorrow ok I think I have an idea of why it resolved to `0.4.10`.

I did a full `cargo update` and found that there's a nested dependency on `socket2@0.4.10` for `async-std-openssl@0.6.3` which we have as a direct workspace dependency.

The nested dependency goes `async-std-openssl@0.6.3 -> async-std@1.12.0 -> async-io@1.13.0 -> socket2@0.4.10`

not sure why it got downgraded when running the upgrade, but this is why it's in our tree at all.

2024-08-22 15:55 UTC, acmorrow commented on Cargo.toml
> +socket2 = "0.5.7"
We shouldn't be upgrading socket2 here.

2024-08-22 15:56 UTC, acmorrow commented
@mattjperez - I was able to get a very targeted update by doing the following:
```
diff --git a/Cargo.toml b/Cargo.toml
index 10e2c5fd..e1381243 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -70,7 +70,7 @@ futures-lite = "1"
 futures-rustls = "0.24"
 futures-util = "0.3.30"
 http-body-util = "0.1.1"
-hyper = { version = "1.2", default-features = false, features = ["server", "client", "http2"] }
+hyper = { version = "1.4", default-features = false, features = ["server", "client", "http2"] }
 ignore = "=0.4.20"
 lazy_static = "1.4.0"
 local-ip-address = "0.5.3"
```

And then:
```
$ cargo update hyper@1.3.1
```

The resulting total diff is:

```
diff --git a/Cargo.lock b/Cargo.lock
index a4075e98..45db9752 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -2070,9 +2070,9 @@ dependencies = [

 [[package]]
 name = "hyper"
-version = "1.3.1"
+version = "1.4.1"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "fe575dd17d0862a9a33781c8c4696a55c320909004a67a00fb286ba8b1bc496d"
+checksum = "50dfd22e0e76d0f662d429a5f80fcaf3855009297eab6a0a9f8543834744ba05"
 dependencies = [
  "bytes",
  "futures-channel",
@@ -2495,7 +2495,7 @@ dependencies = [
  "futures-rustls",
  "futures-util",
  "http-body-util",
- "hyper 1.3.1",
+ "hyper 1.4.1",
  "ignore",
  "lazy_static",
  "local-ip-address",
diff --git a/Cargo.toml b/Cargo.toml
index 10e2c5fd..e1381243 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -70,7 +70,7 @@ futures-lite = "1"
 futures-rustls = "0.24"
 futures-util = "0.3.30"
 http-body-util = "0.1.1"
-hyper = { version = "1.2", default-features = false, features = ["server", "client", "http2"] }
+hyper = { version = "1.4", default-features = false, features = ["server", "client", "http2"] }
 ignore = "=0.4.20"
 lazy_static = "1.4.0"
 local-ip-address = "0.5.3"
```

Which I think is what we want. Could you try that process in a clean tree and see if you reproduce my results? If so, I think that is what we should merge.

2024-08-22 16:05 UTC, acmorrow approved these changes
LGTM with one small question.

2024-08-22 16:05 UTC, acmorrow commented on Cargo.toml
> +hyper = { version = "1.4.1", default-features = false, features = ["server", "client", "http2"] }
Is there a reason to specify `1.4.1` rather than `1.4`? The old requirement was just on `1.2`.

2024-08-23 14:31 UTC, acmorrow approved these changes
LGTM

2024-08-23 16:19 UTC, merged