[RSDK-8963] add support for generic C movement sensor (readings only)
viamrobotics/micro-rdk pull request #326
Opened 2024-10-11 21:31 UTC by gvaradarajan

2024-10-14 13:20 UTC, npmenard commented on micro-rdk-ffi/src/ffi/runtime.rs
> +/// `ctx`, `model` must be valid pointers
add sensor

2024-10-14 13:37 UTC, npmenard requested changes
Done with first pass

2024-10-14 13:37 UTC, npmenard commented on micro-rdk-ffi/src/ffi/runtime.rs
> +/// `ctx`, `model` must be valid pointers
add sensor

2024-10-14 13:37 UTC, npmenard commented on micro-rdk-ffi/src/ffi/runtime.rs
> +        let name: &'static str = Box::leak(name.to_owned().into_boxed_str());
would be nice to change in to a String so we don't leak memory anymore

2024-10-14 13:37 UTC, npmenard commented on micro-rdk-ffi/src/ffi/runtime.rs
> +    if ctx.is_null() || model.is_null() || sensor.is_null() {
update safety section too

2024-10-14 13:37 UTC, npmenard commented on micro-rdk-ffi/src/ffi/runtime.rs
> +    pub(crate) fn register(self, ctx: &mut viam_server_context) -> viam_code {
might consider to call register as part of  from_sensor / from_movement_sensor

2024-10-14 13:37 UTC, npmenard commented on micro-rdk-ffi/src/ffi/runtime.rs
> +        Ok(constructor) => constructor.register(ctx),
If i am not mistaken i think this path can result in a error. If you call register as part of from_movement_sensor you can only have one path for errors which is a bit more readable IMO

2024-10-14 13:37 UTC, npmenard commented on micro-rdk-ffi/src/ffi/config.rs
> +    fn configure(&mut self, mut config: config_context) -> Result<*mut c_void, i32> {
if you are not planning to let user modify if then not sure it should be in a trait

2024-10-17 21:16 UTC, gvaradarajan commented
@npmenard should I close this PR given recent events?

2024-10-22 15:51 UTC, gvaradarajan commented
we're not doing this for now

2024-10-22 15:51 UTC, closed without merging