[RSDK-2619] gpio motor
viamrobotics/micro-rdk pull request #48
Opened 2023-06-05 20:34 UTC by mattjperez

- Verified gpio motors work (`ABMotorEsp32` and `PwmDirMotorEsp32`)
- Make`Stoppable` a Super trait for `Base` and `Motor`

2023-06-05 20:41 UTC, npmenard commented on src/common/motor.rs
> +        info!("stopping motor");
make it debug! or remove it (and if you could do the same for the statement in set_power :P)

2023-06-05 20:42 UTC, npmenard commented on src/esp32/motor.rs
> +//!
This is great

2023-06-05 20:44 UTC, npmenard requested changes
this looks good, once you fix the CI could you also have Gautham take a look?

2023-06-06 16:48 UTC, gvaradarajan approved these changes
LGTM

2023-06-07 19:34 UTC, merged