RSDK-2322 - support configuration for PWM-Direction pin motors
viamrobotics/micro-rdk pull request #60
Opened 2023-06-29 14:13 UTC by gvaradarajan

2023-06-29 17:04 UTC, mattjperez requested changes
Done with first pass. Nice! I like how you implemented the `gpio_motor_from_config`. As much I like turbo fish, I wonder if this might become a bit unreadable if/when we add more motor types.

2023-06-29 17:04 UTC, mattjperez commented on src/esp32/motor.rs
> +                return Ok(Arc::new(Mutex::new(PwmDirectionMotorEsp32::new(
nit: `Self` suggestion

2023-06-29 18:59 UTC, npmenard commented on src/common/motor.rs
> +                AttributeError::KeyNotFound(_) => None,
reading this makes me realize maybe KeyNotFound should disappear and we should return a None instead :P

2023-06-29 19:02 UTC, npmenard approved these changes
LGTM

2023-06-30 14:48 UTC, gvaradarajan commented on src/esp32/motor.rs
> +        ABMotorEsp32 {
so making this change (and the similar change to the other motor) caused the compiler to fail. I think it has to do with the fact that it's an implementation of a generic? I'm looking into it

2023-06-30 15:28 UTC, mattjperez approved these changes

2023-06-30 15:45 UTC, merged